<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectDateandTime</name>
   <tag></tag>
   <elementGuidId>04c7e7a4-5312-4a56-adfe-1936a13b2a98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dateAndTimePickerInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dateAndTimePickerInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18ec4d44-7d61-47e7-9452-3dcaad47b881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c218c13a-4595-4e69-9abe-7c0127a4c09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dateAndTimePickerInput</value>
      <webElementGuid>e58df9e9-dd36-42d9-927d-adf77e9f0620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>November 17, 2023 4:03 PM</value>
      <webElementGuid>4c15bfe1-92f7-4158-97f4-28bfdfb1104c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dateAndTimePickerInput&quot;)</value>
      <webElementGuid>fab66615-841b-4c9c-96b4-592cfc87c197</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dateAndTimePickerInput']</value>
      <webElementGuid>f14a6883-dedb-4ec3-992f-81479480655b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dateAndTimePicker']/div/div/input</value>
      <webElementGuid>c85d1380-47c8-4073-abe9-5d41a5662a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>a1e7ddd3-b569-4281-aeae-b0530b11d4f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dateAndTimePickerInput']</value>
      <webElementGuid>b763cd33-4396-41d7-b479-6df484f4d969</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
