<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_HomeuJrUj</name>
   <tag></tag>
   <elementGuidId>1d925910-9559-4a73-acbd-e71a8545cbad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dynamicLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='dynamicLink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>db3e8541-3975-49c6-bcc9-416f7c9242ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dynamicLink</value>
      <webElementGuid>8cc8ae07-ee22-4cf9-891b-e88886dbd32a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demoqa.com</value>
      <webElementGuid>102a8b58-8857-41fa-8ca2-cb0f916ab271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>12ddb445-2fe8-47b8-8b93-84088f9b504b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HomeuJrUj</value>
      <webElementGuid>3dce04cf-9ca4-4375-ba2c-1e51499b0f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dynamicLink&quot;)</value>
      <webElementGuid>4e2f23b8-e317-4caf-8e04-9b1f10625b4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='dynamicLink']</value>
      <webElementGuid>ddfa6e51-1672-4376-8213-de0e1ec00c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='linkWrapper']/p[2]/a</value>
      <webElementGuid>80f03134-c4fd-4628-accd-f8c7dd63d400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>c9250cb1-6ffb-47e2-b72e-a6396b2420c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Following links will open new tab'])[1]/following::a[2]</value>
      <webElementGuid>702120d3-ad11-4d65-b942-a228c4fa9ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Following links will send an api call'])[1]/preceding::a[1]</value>
      <webElementGuid>906a0657-1918-4453-8553-2cc6ba32d2f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created'])[1]/preceding::a[1]</value>
      <webElementGuid>9b6835b7-c9d2-4c77-8abb-37ca36079e86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://demoqa.com')])[3]</value>
      <webElementGuid>a10ee585-00af-47f0-95a3-f79a778bdf04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a</value>
      <webElementGuid>041d82ed-9833-4a88-b6a3-9f272956ae24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'dynamicLink' and @href = 'https://demoqa.com' and (text() = 'HomeuJrUj' or . = 'HomeuJrUj')]</value>
      <webElementGuid>88dd2f42-5adb-4aa5-917b-a00d48ed564c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
