<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_UploadFilePath</name>
   <tag></tag>
   <elementGuidId>81f93505-9cd3-4f02-9c03-11ba89f7ab11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uploadedFilePath</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='uploadedFilePath']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>87f17960-583d-4806-a1a0-6d9faaf77371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uploadedFilePath</value>
      <webElementGuid>daf77020-0b96-4822-9699-6819ff551d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>C:\fakepath\3.png</value>
      <webElementGuid>b27cf016-6c27-447d-8428-9b7bd0d4cf08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uploadedFilePath&quot;)</value>
      <webElementGuid>d5a2d001-a38d-44c1-a65e-730070afb20e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='uploadedFilePath']</value>
      <webElementGuid>72e401b0-b486-4cb5-9132-a22b00986340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div[2]/div[2]/div[2]/p</value>
      <webElementGuid>aa3dd314-d116-452d-b50e-acb40a69329d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a file'])[1]/following::p[1]</value>
      <webElementGuid>228a199b-ba8b-47b7-bf36-fa2139aeab1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/following::p[1]</value>
      <webElementGuid>c2529119-4528-44ce-a083-8040bbfbdbad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013-2020 TOOLSQA.COM | ALL RIGHTS RESERVED.'])[1]/preceding::p[1]</value>
      <webElementGuid>3d190c2d-5796-4d56-9da0-7ebd5fc96108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'uploadedFilePath', '&quot;', ')')])[1]/preceding::p[1]</value>
      <webElementGuid>309274b8-064f-4c31-a4df-07a637f01301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='C:\fakepath\3.png']/parent::*</value>
      <webElementGuid>c4729a83-05a1-4fb5-beb2-2d4c85300333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>4b085d94-da6b-4913-9c9c-535df11e24d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'uploadedFilePath' and (text() = 'C:\fakepath\3.png' or . = 'C:\fakepath\3.png')]</value>
      <webElementGuid>da826f16-19bc-4594-b5af-6706d268c31a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
